### ISSUE TITLE
-verbose flag

### ISSUE THREAD

**Issue by ChristopheMoreau** [DeclanRussell/IntelOIDenoiser#3]
Hi Declan,

Is there a chance you can add a -verbose option? for removing all the print. (For debugging purposes, when I denoise multiple frames it will be more readable if all the print are hidden). Thanks again for your work.

Chris

**Comment by DeclanRussell** [comment]
Hey Chris,
Sorry for the slow response. Sounds like a reasonable enough request, I'll try and add something soon!

Cheers!

**Comment by ChristopheMoreau** [comment]
Thanks Declan, you rock !

**Comment by DeclanRussell** [comment]
My pleasure! 😄
