### ISSUE TITLE
Progress report

### ISSUE THREAD

**Issue by Xed89** [DeclanRussell/IntelOIDenoiser#4]
I see OpenImageDenoise supports progress functions for filters, it would be interesting. In my project i could intercept the output and show some UI progress. Any chance you can do that soon?

**Comment by DeclanRussell** [comment]
Thanks for the suggestion! Sounds like a nice addition that should be easy enough to add, I'll take a look into it. I'm hoping to get around to adding a couple of things this weekend, but no promises :)

**Comment by DeclanRussell** [comment]
Done! Check out [1.5](https://github.com/DeclanRussell/IntelOIDenoiser/releases/tag/1.5).
