### ISSUE TITLE
Question: linear or sRGB?

### ISSUE THREAD

**Issue by FlorentMasson** [DeclanRussell/IntelOIDenoiser#6]
Hello, 

I need to process images in linear color space (ambient occlusion maps)

The doc states that disabling hdr will assume sRGB:

> -hdr [int] : Image is a HDR image. Disabling with will assume the image is in sRGB (default 1 i.e. enabled)

IODN's doc for RT filter states that srgb is off by default :

<html><body>

bool | srgb | false | whether the main input image is encoded  with the sRGB (or 2.2 gamma) curve (LDR only) or is linear; the output  will be encoded with the same curve
-- | -- | -- | --

</body>
</html>

I see no code here to set srgb to true so I'm wondering, what is the actual behavior? 
If the behavior is actually treating the image as sRGB, I guess I'll have to submit a PR with a new option 😅

**Comment by DeclanRussell** [comment]
Ahh it seems I had overlooked that, thanks for pointing it out. I've exposed a flag for it in fd2f8b2.
