### ISSUE TITLE
The project is not being built

### ISSUE THREAD

**Issue by 8bitniksis** [DeclanRussell/IntelOIDenoiser#7]
![image](https://user-images.githubusercontent.com/57682184/136698573-8598d7e3-327e-4d79-91a4-e56601201bea.png)

**Comment by DeclanRussell** [comment]
Hi @8bitniksis,
You'll need to grab the boost DLLs, (and any other DLLs) from the distribution [here](https://github.com/DeclanRussell/IntelOIDenoiser/releases/tag/1.6). Just download, extract the distribution and put the DLLs in the appropriate places in the contrib folder.

**Comment by 8bitniksis** [comment]
So 
![image](https://user-images.githubusercontent.com/57682184/136711432-3f2c9c3a-1224-4cf3-b7cd-47c5b6fc5624.png)
Dlls in folders, but didn't build

**Comment by DeclanRussell** [comment]
The files need to be in `contrib\win\OpenImageIO\bin`, like in the error you posted above. Though it seems your path is just `contrib\OpenImageIO\bin` (notice the missing `win` directory).

**Comment by 8bitniksis** [comment]
![image](https://user-images.githubusercontent.com/57682184/136711710-00bad9e5-8a86-4a5b-9daf-2b8b662c5cf6.png)
Update folder, but didn't work

**Comment by DeclanRussell** [comment]
Hmm, can you try running scons from the the `E:\Downloads\IntelOIDenoiser-master\IntelOIDenoiser-master` directory?

**Comment by 8bitniksis** [comment]
:D It's work, big thx

**Comment by DeclanRussell** [comment]
Great to hear 😄
